spring:
  jmx:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    validate-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://exporteru.com/api/v1/oauth2/callback/google"

  data:
    redis:
      password: ${REDIS_PASSWORD}
app:
  datasource:
    write:
      url: ${MASTER_POSTGRES_URL}
      username: ${MASTER_POSTGRES_USERNAME}
      password: ${MASTER_POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
    read:
      url: ${SLAVE_POSTGRES_URL}
      username: ${SLAVE_POSTGRES_USERNAME}
      password: ${SLAVE_POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
    #========= Hikari Pool =========#
    hikari:
      maximum-pool-size: 16
      minimum-idle: 4
      connection-timeout: 3000
      leak-detection-threshold: 20000
      auto-commit: false
      idle-timeout: 30000
