server:
  port: ${PROD_PORT}
logging:
  level:
    root: ${PROD_LOG_LEVEL}
spring:
  mvc:
    cors:
      allowed-origins: ${PROD_CORS_ALLOWED_ORIGINS}
      allowed-methods: ${PROD_CORS_ALLOWED_METHODS}
      allowed-headers: ${PROD_CORS_ALLOWED_HEADERS}
      allow-credentials: ${PROD_CORS_ALLOW_CREDENTIALS}
      max-age: ${PROD_CORS_MAX_AGE}
  datasource:
    url: ${PROD_POSTGRES_URL}
    username: ${PROD_POSTGRES_USERNAME}
    password: ${PROD_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: false