spring:
  datasource:
      username: ${CONTAINER.USERNAME}
      password: ${CONTAINER.PASSWORD}
      url: ${CONTAINER.URL}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    user: ${CONTAINER.USERNAME}
    password: ${CONTAINER.PASSWORD}
    url: ${CONTAINER.URL}
    enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:8080/api/v1/oauth2/callback/google"
app:
  frontend:
    oauth:
      google:
        redirect:
          success: ${FRONT_END_HOST}/site/index.html
          error: ${FRONT_END_HOST}/site/index.html
