spring:
  datasource:
      username: ${CONTAINER.USERNAME}
      password: ${CONTAINER.PASSWORD}
      url: ${CONTAINER.URL}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    user: ${CONTAINER.USERNAME}
    password: ${CONTAINER.PASSWORD}
    url: ${CONTAINER.URL}
    enabled: false